"""

Auto-generated from CDL model: MyController
Generated by: CDL to Python Translator
"""

from typing import Dict, Any
from cdl_python.CDL.Reals import Add
from SubController import SubController


class MyController:
    """
    """

    def __init__(self):
        """Initialize MyController

        Args:
        """

        # Instantiate CDL blocks
        self.add2 = Add(
        )
        self.subCon1 = SubController(
        )
        self.subCon2 = SubController(
        )

    def compute(self, u1, u2) -> Dict[str, Any]:
        """Compute outputs

        Args:
            u1: Real input 1
            u2: Real input 2

        Returns:
            Dictionary with outputs:
                'y': Real output
        """
        add2_output = self.add2.compute(u1=u1, u2=u2)
        subCon1_output = self.subCon1.compute(u=u2)
        subCon2_output = self.subCon2.compute(u=u2)

        return {
            'y': add2_output['y'],
        }