"""info=<html>
<p>
Block that outputs <code>y = min(yMax, k*e)</code>,
where
<code>yMax</code> and <code>e</code> are real-valued input signals and
<code>k</code> is a parameter.
</p>
</html>

Auto-generated from CDL model: CustomPWithLimiter
Generated by: CDL to Python Translator
"""

from typing import Dict, Any
from cdl_python.CDL.Reals import Min, MultiplyByParameter


class CustomPWithLimiter:
    """info=<html>
<p>
Block that outputs <code>y = min(yMax, k*e)</code>,
where
<code>yMax</code> and <code>e</code> are real-valued input signals and
<code>k</code> is a parameter.
</p>
</html>

    Parameters:
        k: Constant gain
    """

    def __init__(self, k=2):
        """Initialize CustomPWithLimiter

        Args:
            k: Constant gain
        """
        self.k = k

        # Instantiate CDL blocks
        self.gain = MultiplyByParameter(
            k=self.k,
        )
        self.minValue = Min(
        )

    def compute(self, e, yMax) -> Dict[str, Any]:
        """Compute outputs

        Args:
            e: Control error
            yMax: Maximum value of output signal

        Returns:
            Dictionary with outputs:
                'y': Control signal
        """
        gain_output = self.gain.compute(u=e)
        minValue_output = self.minValue.compute(u1=yMax, u2=gain_output['y'])

        return {
            'y': minValue_output['y'],
        }