"""Sub controller that multiplies input by 0.5

Auto-generated from CDL model: SubController
Generated by: CDL to Python Translator
"""

from typing import Dict, Any
from cdl_python.CDL.Reals import MultiplyByParameter


class SubController:
    """Sub controller that multiplies input by 0.5
    """

    def __init__(self):
        """Initialize SubController

        Args:
        """

        # Instantiate CDL blocks
        self.gain = MultiplyByParameter(
            k=0.5,
        )

    def compute(self, u) -> Dict[str, Any]:
        """Compute outputs

        Args:
            u: Input signal

        Returns:
            Dictionary with outputs:
                'y': Output signal
        """
        gain_output = self.gain.compute(u=u)

        return {
            'y': gain_output['y'],
        }